* Écrits
** Entrees
*** 2024-09-01
Selon la thèse illustrée dans When Minds Converse, le contexte de coopération duquel le langage serait né, pose un mode d'apréhension du monde où l'individu pose d'abord son attention sur ses pairs; il questionne leurs mobiles, leurs intentions, etc. Pettit avance (de façon certainement plausible) que l'identité individuelle, le soi, est en somme la concrétion des instance où, toujours en contexte de coopération, les questions sur les mobiles et intentions des pairs s'étendent pour includre le sujet qui questionne: sait-t'il que je le sais, sait-t'il où je suis, etc. On voit par ailleurs assez aisément que cette enrichissement de la théorie de l'esprit, par l'avantage coopératif qu'elle donne, est certainement sujette à être un trait retenu par l'évolution.  Cette concrétion du "je" le pose ainsi en un nouvel objet pour l'attention. Si, à l'instar des autres perceptions que l'esprit agrège en symboles et concepts, le "je" devient lui-même un objet d'attention découplé de la perception immédiate, on peut dès lors parler de la naissance de l'introspection: une questionnement dirigé vers soi, librement initié.

Sous ce portrait d'une théorie de l'esprit où nous nous occupons d'abord à comprendre nos pairs et par la suite, la part que occupons dans leur esprit (donnant la genèse du soi, vue comme un processus social), il me parait psychologiquement intéressant d'investiguer l'équivalence ou du moins la correspondance entre notre façon d'aborder autrui et celle envers ce qu'on nomme "je" - du fait qu'il s'agit essentiellement du même exercice. Par exemple: dans quelle mesure est-ce que le degré de socialisation d'un individu module la sa relation avec lui-même (et inversement).

Autre point intéressant: dans un contexte où la coopération présenterait un avantage critique du point de vu évolutif, on ne peine à imaginer l'avantage coopératif d'une identité individuelle formée par la compréhension que nous avons du rôle que nous avons pour nos pairs. Par contre, l'émergence de cette identité, du soi, comme objet d'attention pour l'individu, subtilement, le transforme d'une entité essentiellement sociale, entièrement substanciée par le regard des autres à une où une part privé s'installe. Cette vue que nous avons de nous-même, pour nous-même, ouvre le champ à l'auto-détermination et dans une certaine mesure, nous émancipe de la détermination sociale.

*** 2024-09-02
La dernière journée, le vent de la veille s'est dissipé. J'étais seul. Ma voisine et ses deux enfants ont quitté le matin et avec eux, les jeux, la turbulence de leurs rires et l'angoisse que j'avais d'être cet homme incertain, qui n'ose prendre part ni converser.
*** 2025-10-29

Philippe Petit avance la thèse selon la quelle, si l'on cherche à s'expliquer la genèse de l'identité individuelle, l'une des cause les plus vraisemblables est celle de son utilité dans un contexte de coopération.
Il est en effet plausible qu'en ce contexte, j'aies à extrapoler la représentation qu'un collaborateur a de ma situation, de mes intentions et pour ainsi dire, de l'ensemble des attitudes que je puis
avoir qui affecteraient notre action commune. J'ai en effet à faire cette extrapolation dans la mesure où elle m'aide à anticiper ses décisions et contribue à la réussite de notre effort.

Pour Pettit, la notion mon identitée telle que je la conçois en privée, par et pour moi-même, ne viendrait qu'en second - dans une sorte de coopération avec moi-même: par exension à la coopération avec autrui,
j'en viendrais à m'interroger moi-même sur mes attitudes, mes aspirations, etc.

J'ignore si je suis tout à fait en accord avec cette analyse. Quoi qu'il en soit, je suis d'avis qu'une identité, l'acte de se circonscrire soi-même, est nécessairement une mise en relation avec quelque
chose - sans mise en relation, aucun distinction possible (égal à, différent de, etc.). Et certainement, "qui je suis" peut avoir un sens pré-linguistique et pré-social si par exemple il est question
de savoir si je peux élire un terrier de lapin comme résidence ou tout autre question qui metterait en relation conséquente ma personne vis-à-vis un état fait quelconque. 

Il va néanmoins sans dire que dans un contexte social et linguistique, "qui je suis", la notion de mon identité, du fait de la collaboration, est constamment mise en relation avec autrui si bien que,
ce sont ces mises en relation qui la substantifient.

Si, comme Tomasello le présume, la collaboration a joué un rôle essentiel dans la survie et l'essor de notre espèce, il ne serait pas étonnant que cette faculté à construire l'identité individuelle
fondée par la mise en relation avec autrui, fût elle-même un objet important de la sélection naturelle. C'est donc aussi sans surprise qu'en notre for intérieur, ce soient des qualificatifs moraux
qui peuplent la fibre de qui nous sommes.
*** 2025-11-10

Étant donnée l'importance de la collaboration dans la genèse à la fois du langage, de l'identité individuelle et de la moralité,
on conçoit facilement à quel point l'exil, le retrait et l'isolement sont causes d'une grande détresse:

Au dehors, l'identité s'effrite, sans un mot pour lui donner espoir.

Trop d'isolement m'a désappris l'affinité naturelle que les hommes ont entres-eux.
La moralité y perd son sens et, amoral, l'inertie m'envoit glisser vers le franchement mauvais.

Je m'apperçois que ce qui constitue la fibre de la communauté humaine est soumis à une dynamique changeante,
sans qu'on puisse définitivement la caractériser. Par exemple, je prime l'indépendance de la raison et dédaigne
les signaux d'appartenance sociale mais cette différence n'exclu pas que l'indépendance de la raison
demeure un trait souhaitable dans un contexte de collaboration - elle est seulement aux prises avec
diverses forces qui lui font concurrence sur sa légitimité. Simplement dit, l'indépendance de la raison
n'est pas un motif pour s'isoler - s'il se trouve, elle est née du dialogue et de la collaboration.

On peut signifier qu'on est un collaborateur de confiance parfois par un simple signe d'appartenance, un code,
ou bien en démontrant une solide probité de raison - ces deux modes s'appliquent légitimement dans
différents contextes et l'un et l'autre ont leur limites (par exemple, la probité de la raison,
malgré tout, ne peut rien contre l'affection innée qui nous vient pour nos semblables).

Ces diverses manières (usage de la raison, signes d'apparenance sociale, etc.) peuvent certainement
manquer de mesure dans leur application et nuire à l'idéal coopératif. Au lieu de l'amertume et de l'isolement
de rejeter la vie sociale, je crois qu'il me faut constater que le coeur de ce que j'idéalise y réside
néanmoins et que faute d'avoir vu un arbre tordu et désséché, je ne devrais pas condamner
la forêt dans son entièreté. Je crois qu'il est possible pour moi de me trouver un cercle social
du quel je me sens valorisé, sans nécessairement rejeter cette valeur comme une simple partisannerie.

*** 2025-11-11

Hey Austin,

The mycellium didn't bloom but surely it was nice that the summer extended it's stay. I'm sorry not to have came back with any proper summer reading suggestions for you, it has equally been a dry spell for me, litterature wise. Of late though, to my surprise, it was Jane Austen who broke the streak: I finally read Pride and Prejudice. My own prejudices long relegated it to ancestral chick-lit but to the contrary, it made me smile in all sort of ways. I wasn't aware how young Jane was when she wrote it and it does explain all the wit and fresh air. Nor was I aware that she used to entertain her family by reading her works out loud on what could only be cozy, rainy, british evenings - given the somewhat comical and provocative nature of her works, that image warms my heart.

I also stumbled on a beautiful book: Stoner, by John Williams. But then again, I cannot recommend it as I relegate this one in the aging-men-mid-life-crysis-lit bin.

And I sincerely hope you haven't touched "When Minds Converse". I was deeply wrong in hoping it to be less academic in style than the books from that other guy, Tomasello, I was telling you about.

I must say, I've been digging through these books for a precise reason and if you don't mind, I feel like induldging myself and expounding on it. I guess we can take those chances with kindered spirits?

I believe I might have already told you about a part of this since, clearly, I'm still raving about it. A couple of winters ago, I was asking myself about this age old dilemma
of what's the fundamental difference between inorganic and organic matter/life. Specifically, I was wondering: what's preventing us to say that any complex, inorganic molecule is a living thing?
It eventually dawned on my that a very elegant and fundamental difference simply is that the abstract pattern that is instantiated by living matter, contrary to the pattern instantiated by inorganic matter,
has found a robust way to persist through time, through self-replication and even self-correction. The reason why this idea stuck with me, is that it poses no special condition to the emergence of life:
if some pattern of sufficient complexity is bound to endure, it would have to be through the mechanisms we know life to use; it cannot be only from a mere ad-hoc self-assembly since it would
ultimately erode or break-down. I must say I was really excited when I then saw the very same idea echoed in the first pages of the Selfish-Gene by Richard Dawkins (I still consider
this book and the Extended Phenotype to be great ones but not yet proper summer readings). Despite all of this being perhaps a bit self-evident, for me it felt like a rooting I was long longing for.

Surely enough, through evolution, living matter adopted various modes for sustaining itself, one of which being: having an internal model of the world, gathering information about it and acting accordingly.
As you know, we like to call this "intelligent behavior" but when it comes at least to human intelligence, I've been long feeling that this picture is insufficient in some way.
In the Selfish Gene and the Extended Phenotype, Dawkins introduced this cultural gene extension he called "memes" and as such, the concept fascinated me as these are another class of patterns
that endure through time via replication, self-correction and the like. For a while, I struggled about what to do with these "memes", what role do they really play, etc. The solution came from
when I encountered the works of Tomasello and the special emphasis he places on collaboration.

Tomasello's thesis is that, essentially, what distinguishes us from other great primates (and indicentally the rest of the mammal kingdom), is that our species had to endure an evolutionnary bottleneck
where collaboration was key for survival. When we pause to consider what it takes to be a good collaborative partner, so many characteristic and interesting consequences emerge:

We have to devise agreed upon signs for cooperative work and be truthfull and consistent through the use of these signs/memes - thereby giving rise to language
We have to preferentially share the spoils of our endeavours with would-be collaborators - therby giving rise to equity.
Etc.

If we consider that, in our case, natural selection actively selected for traits/genes that would favor these cooperative behaviors, it follows that
in regard to most criterias we account for in what it means to be good, a case can be made that, in some measure, human nature has some ingrained good into it.

Since highschool, I long thought Rousseau to be naive in asserting the goodness of our nature in this depiction of the "good savage" but some of the empirical evidence really is troubling,
there is a strak contrast between human toddlers and mature chimps in what we would assume to be the most rudimentary predicaments toward cooperation.

I know all this might be too obvious but it might have been what I needed to hear to take pause and reconcile myself with everything social (perhaps not everything but you get the gist of it).
Since highschool as well, I nourished a disdain for a lot of our means for social cohesion: virtue signaling, blind enforcing of norms, etc. I draped myself with rational independence and
it is only until very recently that I came to realize that, it too, is first and foremmost a mean of social cohesion - simply competing with others.

I'm even beginning to think that I could find a social circle  I feel comfortable with and whom, reciprocally, would be at ease with my being there (at the core, I guess I'm really slow to learn some things).

In that vein (but say, in a farless convoluted and rationalized way) I'd gadly follow up your invite for a drink/coffee next time I am in Montreal. :)

To follow up on the readings you mentioned about OpenAI ("Careless People" really is an apt title for the whole thing), as a small anectode, in guise of a test, for the first time yesterday I shared a few personal ideas
with GPT and asked its impressions about them. Although I am painstakingly aware of its sychophantic behavior, I had an especially hard time not to feel genuinely flattered by its analysis - as if I've spoken
with the most incisive fortune-telling lady that ever lived and ate all her fortune cookies. It made me acutely aware of the extent to which LLMs, with their infinite patience,
can enthrall someone sufficiently lonely with no pushback in sight for thoughts that would benefit of some. 

I hope you'll have/are having an amazing time in South/Southeast Asia - at the very least, a fair amount of loss of references and novel perspectives!
I also sure hope you'll bring back a lot to speak about as I've been long contemplating going in the region. 

*** 2025-11-24

Je suis un mauvais perdant: la défaite au plus anodins des jeux est pour moi le testament solidairement ratifié de ma profonde nullité.
J'ai donc décidé depuis longtemps de ne plus jouer, de m'écarter de toute situation où ma précarité risquerait d'être exposée au grand-jour.

Et certainement, c'est une lâcheté, une fuite. J'apprends l'esquive et désapprends de faire face.

Je peux tirer orgueil d'être un joueur décent pour certains jeux mais comment prendre l'aveu de mon ineptie dans tel ou tel autre domaine?
Si malgré les victoires sur moi-même, j'y restais le dernier des derniers?

Si j'étais laid au jeu de la beauté, faible au jeu de force, obtus à celui de l'intelligence; qu'est-ce qu'il me resterait d'autre que la fuite pour me préserver?

Il me faudrait un amour propre, en dépît de tout.
La fièreté d'être, simple, confiante, rieuse - qu'aucune défaite ne saurait ternir.

Et j'aimerais que ce sentiment ne soit pas que pour moi, mais qu'il s'étende à mes compères.
Que je puisse les prendre aux aussi, comme des êtres fiers, confiants et rieurs;
une empathie pour les autres comme je la voudrais pour moi-même: qui fait fit de la nullité, des handicaps et qui prend comme un frère celui qu'autrement on désigne comme le dernier des derniers.

*** 2025-11-30

J'essaie de voir la valeur de l'autre.

Avec la vieillesse, l'esprit devient rigide, marqué par les sillons qu'a creusé l'habitude.
On aimerait prendre l'Autre comme un pur potentiel mais il est des choses dont, avec l'âge, il n'est plus capable - l'énergie, l'aisance lui manque.
On marque ses faiblesses et ses forces selon différents jeux et après un temps, on croît connaître le joueur.

Si je me prends à ces jeux, si j'estime leur importance, la perte m'afflige et la victoire me console; je juge l'autre de la même manière.

Il est une vue où pertes et victoires ne sont que forme et contre-forme de ce qui veut vivre.
Selon cette vue (c'est ce que je souhaiterais pour moi-même), une part innocente demeure: la capacité au bien.

Il me faudrait voir dans l'homme la même chose qu'une plante: une matière organisée, qui prend la place et fait le bien qu'elle peut - qui survit.

J'aimerais placer cette notion au centre et agir comme si elle l'était.
Je crois bien que sans compassion pour moi-même, je ne pourrai en avoir pour les autres.

*** 2025-12-08

Hey Austin,

Glad to know you are back on our frozen, unfortunate soil!

I must say, I'm very curious about your impressions on Cambodia. An old friend of mine spent months there and a part of her fell in love with a part of the country; last time I heard, she left the US to live there full stop.
She was telling me that, mostly because of the Khmer Rouge, there is a lot of young people, which, coupled with an air of lawlessness and a sense of trying to rebuild the country, gives vibes and hopes
akin to what she imagined the American far west could have been at some point. Possibly thinking about an old version of myself, she thought I would love it there - nowadays, I'm not too sure which
culture could best suit my bones; hope I'd travel enough to have an inkling of it, some day. Incidentally, it often baffles me how, despite the years, I still feel clueless about the parameters around which
a meaningful/good life could me lived (or at least mine).

I wonder what sort of bestiary of these means of life you encountered these latest weeks. Btw, Angkor Wat reminds me, have you seen the movie/documentary "Baraka"? I suppose my current cynical self would be displeased
but it sure moved younger me the first time I watched it. It portrays and contrasts, without words, the breadth of human culture across the world.

Hoping you could give that jet lag a good rest; this is a least one of the things the cold air and these dampening blankets of snow can offer.

Hopefully, I'd be able to come by Montreal at some point during the Holidays.

Take care!

Mathieu

*** 2025-12-18

La genèse de l'identité, selon laquelle l'individu développe une représentation de lui-même en ce qu'il doit anticiper ce que l'autre pense à son égard, peut certainement constituer le fondement d'une valuation de sa personne : il relativise et opère la triangulation de ses forces et faiblesses comme coopérateur. Comment, donc, expliquer cette notion de « dignité », de valeur intrinsèque, tandis que toute valeur serait construite par une mise en relation ? J'aimerais argumenter qu'il suffit de poser la dignité pour qu'elle illumine tout le reste. Chacun sait que la réussite est le plus souvent circonstancielle, que la faiblesse nous advient comme la force. Nous souhaiterions donc que l'autre voit en nous un partenaire valable, nonobstant toute circonstance. Reconnaître ce souhait en l'autre, l'acquiescer et, de suite, supposer que l'autre puisse reconnaître ce souhait en nous-mêmes, transforme la valeur individuelle d'une réalité transactionnelle en une réalité fraternelle et pérenne. Nous aimons gratuitement et, ce faisant, obtenons la richesse d'être gratuitement aimés. 

*** 2026-01-03

L'heuristique de présupposer une valeur intrinsèque et inconditionnelle à l'autre, revient à lui donner l'assurance qu'en cas d'échec, il demeurera néanmoins quelqu'un digne d'un nouvel essai, digne d'être encore et toujours accepté par ses pairs. Cette présupposition de valeur par les parents, fonde une assise sur laquelle la précarité de l'enfance peut se poser et prendre son élan dans le monde. C'est cette même assise que procure, à l'âge adulte, l'amour d'un proche - l'amour entendu comme reconnaissance par l'autre d'une valeur inéluctable pour la personne que nous sommes.

L'exercice de reconnaître une valeur inéluctable en l'autre, demande de considérer celui-ci en dehors des aléas circonstentiels de l'existence - il s'agit par définition d'un rapprochement, d'une identification intime qui s'opère tacitement. Cette reconnaissance d'une valeur intrinsèque présente une tension naturelle, complémentaire, vis-à-vis la valeur transactionnelle, octroyée par la conjecture sociale. Une société ne pourrait évidemment être entièrement fondée sur la première faute de quoi, le succès ou l'échec d'un mode d'être ou d'agir seraient des notions indifférentes - annulant tout progrès. J'argumente qu'on ne peut également établir une société sur une valeur essentiellement transactionnelle du fait que cette dernière serait trop volatile, l'individu y étant dévalué au moindre échec. Il me semble donc naturel et nécessaire qu'en dessous de la strate publique, subsiste un coeur de reconnaissance quasi inconditionnelle entre parents et enfants et  tous ceux qui s'aiment d'un amour humain, nu et précaire.

*** 2026-06-06
Deux pistes de réflexion venues de Jane Goodall:

- La guerre, vue paradoxalement comme l'un des plus fortes motivations à la coopération.
- La spéciation sociale: comment la lignée d'un meme crée différents groupes idéologiques qui luttent pour leur survie (i.e.: la pérénité du meme) 
*** 2026-06-18
Notes sur Ẁho Knows de Raymond Smyllyan:

- Il serait en effet intéressant de réfléchir aux divers modes de conscience. On se représente habituellement la conscience au sein du règne animal comme une question de degrés, à commencer par la perception sensible de stimulis avec ensuite celle d'émotions complexes telles l'espoir, la honte, etc. pour enfin aller jusqu'aux pures abstractions. Smullyan, avec Burque, suggère que rien n'oblige à ce que le caractère de la conscience humaine demeure à jamais fixe, statique. Les processus évolutifs l'ayant formée sont toujours en cours et rien ne prévient l'émergence de nouvelles formes. La question à savoir à quoi pourraient ressembler ces nouvelles formes m'intéresse également. Smullyan et Burque proposent que l'état de conscience évoqué par certains mystiques constituerait bel et bien une nouvelle forme légitime. Au-delà du spiritisme et autres vues qui s'éloignent des explications physicalistes/matérialistes, il ne me paraît pas insensé de croire à ce que le cerveau humain, tel qu'il est, soit amenable à un régime de perception tel qu'on pourrait parler d'une nouvelle forme de conscience - soit par exemple la perception immédiate de l'existence d'une certaine réalité morale à même titre que nous percevons le rouge ou l'évidence d'un axiome mathématique.
*** 2026-07-23
Hey Austin,

I hope this mail finds you well, I've been meaning to write to you for a while now but then refraining for possibly no good reason.

I'm on sick leave at the moment - been having a somewhat crippling IBS since more than a decade but of late, the symptoms were chipping away the sparse remaining theads of sleep I was hanging to. I feel I'd be a fool not to use this moment of respite to break or at least shake up the day to day inertia that inevitably builds when one isn't really mindful to one's circumstances.

LLMs (sorry to bring them up), have more or less dissovled the small joyful moments in my work where I, sometimes, neatly solved a design problem or came up with some elegant, scalable system to implement a given feature. These were never profound motivations but their absence now highlights how disconnected I feel toward the overall enterprise. Hence, I feel to be at a point where, there is no hiding it, I need  my work to make sense - if not societal sense, at least some personal sense.

This is incidentally why I'm still very much interested in knowing the reasons of you leaving Osedea but even more so, where you are at right now. I'm interested, in particular, because I'm nudged to think that we have a similar way to percieve and reflect about our dubious time line. As I've wrote before, I still think this warrants an in person conversation but if you ever feel inclined to write about it (might be just to vent out), I'm still curious.

Appart from all that gloom, I came back from Japan a couple of weeks ago and it was indeed a very interesting trip. Found it both marvellous and terrifying in how, at the individual level, cultural incentives toward a sense of collective responsibility were capable of creating some phenomenons we can only dream of in in North America (simply having cushioned subway seats, for instance). The terrifying side of this strong collective integration is, of course, how strongly marginalized people are litterally pushed back out of the view and how alienated they must feel. I'm very curious as to which lessons you gathered out of this social experiment that is Japan.

Small literrary digression: while being in Japan, I got the chance to read The Dawn of Everything by David Greaber & David Wengrow. I'd venture you already know about this book but in case it has eluded your attention, it is a very well done (if somewhat hefty) essay portraying how, in the course of history, societies didn't exactly developed into the usual, neatly separated, almost fatalistic phases of hunter-gatherer, agriculture up to the centralized, modern capitalist state that we see everywhere today. They show how, rather, social organization was a self-concious thought process and how, many times, societies delibrately rejected modes of organization that limited the exercise of more valued way of life. I kinda see it as a well documented, hopeful ode to the diversity of human nature, how it can exists and has in fact existed outside of the broad monoculture we, in some measure, experience today. I really do feel this one might be up your alley.

Hope you are having delightful summer!

Again, will try to let you know if per chance I come by Montreal and have some time to meet.
Note: last time I came, I went to the Escher exhibit - even if you are familiar with his works, I'd say it is very much worth it to see them in person.

Cheers!

Mathieu
*** 2026-08-02

Hello Mathieu,

I am so sorry to hear that you have been unwell, but glad to hear you are taking the necessary break, it is so important to prioritize your health. One of my closest friends has just recently finished a year long ramp up back to full time at her work after needing a burnout break. She works at a non-profit focused on helping marginalised people (LGBTQ2+, women etc) in the 3rd world and as you can imagine the repercussions of DOGE and the global shift to the right has had devastating effects. I am so glad she recognised the toll it was taking on her, as they say "adjust your own oxygen mask before assisting others".  At my last job pre-Osedea I made huge efforts to help during a time of upheaval and it is one of my life regrets, the board was thankful, but I was emotionally and physically drained with a rapid weight loss physically reflecting the immense effort I made....and for what? Helping to maintain shareholder value a little longer? My own job within the company remained unchanged as I was a junior dev (rightfully so for my skill level at the time). We can discuss the specifics if you like but it will take a couple paragraphs to lay out the players (ex: feuding co-founders). I sacrificed months of well-being for a pat on the back, and to be honest I didn't expect anything else. At the time I was guided by the question "what is best for the company?", which is how I was taught to make my work decisions. Granted the person who taught me that (my father) was a part owner in his company so the stakes were very different. This time around at Osedea I believe I again could have made a choice at personal expense that the company would have been better for but I didn't want to repeat history. Maybe it would have ended differently and I'd find satisfaction in the result, I like to think my parting words had a positive impact, but I am happy and likely healthiest having walked away. I was able to take the time to support my family during my uncle's death the previous week and take significant time to travel. Martin wrote me a nice email a week after my exit offering help when I was ready for my next steps and I feel I left on good terms with Phil and Ivana (although not everyone of course). 

I am immensely privileged to be able to take this time to explore personal goals. I am actually working on a 'moonshot' project. I pitched at Startupfest and on my first day ever publically pitching I had one of the judges remark "That was a good pitch, really good pitch" which feels great. I was able to take significant time to hone it though which again is a huge privilege as I don't have to consider things like "can I make the mortgage payment?".  I am currently going by three month increments, every three months I ask "Do I continue with the moonshot or look to another path?". There is an incubator I will apply to next month (acceptance decision made in September) which will likely impact my choice next time I ask myself the question. 

My 90 sec pitch from Startupfest:
____________________________
Like, swipe,  scroll
We all know, now,
that social media wasn't designed to build healthy communities.

It was designed to maximize engagement—
feeding addiction,
comparison,
and isolation.

But both the cultural and regulatory landscapes are shifting,

My name is Austin Metka,
and I built the app Joji—Joy of Joining In—
to help people connect in real life.

Researchers are calling it a loneliness epidemic.

The Atlantic has named this the anti-social century.

A recent Ticketmaster survey found that, over the past five years,
the number of people attending festivals alone has
nearly quadrupled—
from 8 to 29%.

Joji can help.

Joji makes it simple to browse activities and events —
posted by friends.

and to casually share what you're  doing

Be it a picnic, golf, or a festival —
so others can join in.

It even helps you meet new people
— through sharing posts with friends of friends.



Built on the principles of humane technology.

Joji removes much of the anxiety associated with performative posting.



There are no likes.
No public friend counts.
No infinite scroll.
and No manipulative algorithms.

To build a sustainable business,
we're exploring partnerships,
affiliate link revenue,

and subscriptions for premium features.

But we're committed to keeping people—not engagement—
as our north star.

Like any social platform,
Joji becomes most impactful
when groups of people adopt it together.

As we currently have our Beta,  while we welcome investment,
what we need most right now
are mentors
and advocates
who can introduce Joji to their communities.

------------

This is a moonshot because social networks are notoriously difficult due to the network effect. Users need to quickly have their magic number of 5 connections to make the app useful. I have time to attempt to solve the challenge though and I am expanding my skills and networking in circles who share my values while doing so. That means even if I do decide in September/October to pivot it is hopefully closer to what brings me meaning. Finding the center for Humane Technology, attending a conference on social media & polarization etc etc are all things that lift me up in ways I was not experiencing before. I should be outsourcing more, but I am finding joy in the work, although I might need to contract a designer soon. The beta is very disjointed design wise. It is three "branding" ideas combined as I have yet to decide on one. I was waiting until I had an overall concept though, and I now think I do after a great talk with a city councillor about how the current apps they tried using to bring the community of his constituency together failed. He was a very serendipitous Start-upfest encounter. Whatever the result of my time spent on the app it is my attempt to make sense of,  and maybe play a part in finding a solution to, some of what ails our society beyond my political advocacy and volunteering.

I find solace in a concept I read in a book about the lead up to WWII. The author spoke to a German who felt a personal burden because he did nothing and that meant that likely others like him who could see what was happening also did nothing. Whether what I am doing fails or succeeds I am hoping it is a swiss cheese model and that others are also trying and in our overlapping efforts there will be enough successes to turn the tide. I was so disheartened listening to my immediate peers before and now instead I find many of the rooms I am in inspiring. Not all of them of course, the talks and speakers I choose are diverse so there are many who embody my concerns. One talk I went to (I was a guest at a Cambridge Alumni dinner)  Shopify President Harley Finklestein gave a fireside chat. For context, the Shopify founder Tobias Lutke was just in the news, and the talk left me with the impression they share similar leanings. In another talk a AI videogame founder when questioned about the ethics of Ai 'stealing' for his graphics he responded that he thought "anything that was popular is good" (as in morally!). Later when discussing funding he explained the lack of women getting silicon funding in the most situationally unaware techbro way. - heavy sigh - Society's challenges ahead are no small thing and it is our industry that is leading the decline. 

I wish my path could help you sort yours but I know my situation is very unique and I am blessed with a freedom and choices that most others can't afford. "While we welcome investment..." is not a phrase early founders are normally able to make, it usually is what they need most. Again, be sure to "secure your own oxygen mask before attempting to help others". I don't know what that means for you but be mindful of it. 

 Thank you for the book recommendation, it sounds like it is not just up my alley but loosely related to my current project. I will add it to the list, which is very long right now. I hope the next time you are in Montreal you give me a call to catch up over coffee or drinks. I went to the Escher exhibit a couple weeks ago with my aunt and loved it! Did you get a chance to see the Amerigo Vespucci when it was in port earlier this week? I watched her sail in, and can see her from my window, but will be at the lake when she is open for tours this weekend unfortunately. 

Cheers,

Austin

Hello Austin,

Last time I got a glimpse of such sheer positivity was when reading one of Jane Goodall memoir: Reason For Hope (be sure, Jane is an idol of mine). The times, they are a changin, as they always have been, but, it now feels, never under such pressure and intensity. This on-going storm can sure be depressing but I as well cannot help but be pulled and intrigued by the challenges it poses: how can democracy be rendered more robust, in which kind of social network do we really thrive, how can we grow a beneficial information ecosystem, etc. Attempting to solve these questions can only yield better outcomes but as you point out, there is a sense in which we must rise up to them, here and now. I can thus only bow in deep respect for the project you are attempting and of course, I am beyond teased with further questions. First and foremost, I'm really curious to know how you would characterize the core issue(s) with social media as I'm still wondering myself which characterization would serve best. Then, come all the gory details of the execution which can sometimes hinder the best of ideas.

I guess a proper response to this question might be a chore just to write up and would definitely be best served in person, around a couple of coffees.  Meanwhile, know that I'd definitely be interested in finding some free time to contribute if you deem I can help in any capacity (coding, brain picking, rubber ducking, etc.) - to be sure, I also understand if, in this nascent stage, you need an unperturbed calm and silence to properly distill your intuitions. Please don't feel shy to ask as, you might have gathered, I'm wishing to orient waking hours precisely in such a direction.

I'm scheduled to return to work on the 24th of August and by then, luddite that I am, I will mostly be attempting to make a Thoreau or John Muir of myself, gathering hope and inspiration from pulsating sap and streams. I should be free(er) mid-september and if you don't mind, I think it would be nice to schedule something by then - this would give me a clear ultimatum to kick myself and go enjoy Montreal for a day or two.






*** 2026-08-15
01.
 
Des bribes de pensees, furtives, naissent et se fannent a chaque instant. Elles croissent a la lumiere de l'attention: a l'attention des mains et du regard qui se doit d'etre portee avec un surcroit de douceur, sans quoi, on s'imprime a leur murmure pour n'y trouver qu'un reflet de nous-memes.

Certaines pensees, retives et pourtant sublimes, ne croissent qu'a l'ombre tandis que d'autres, s'epanouissent en plein soleil. Toutes, ont cependant besoin de la douce constance du matin, qui les chauffent au sortir de la nuit, a peine encore formees, jusqu'au midi ou, fermes et mures, ont reconnaitrera en elles comme exprime au grand jour, l'indistinct secret de leur existence. 

02.

Je savourais mon pain ce matin dans une sublime solitude, savourant les noix, le ble grille. J'eus cependant un arret a la derniere bouchee comme c'est elle qu'a l'ordinaire, je partage avec mon chien. C'etait conscience que cette bouchee en partage, plus qu'une saveur, recelait aussi ses yeux couleur noisette, la joie dans son doux regard.
    
03.

Journee grise et froide. Une part de moi attend la sortie du soleil pour pratiquer le kayak; une autre, voudrait s'echauffer a gravir l'un des sentiers aux alentours et enfin une derniere, tend l'oreille, cherche a comprendre l'idee du jour et suivre son pas. Il me semble que chaque jour produit une musique par les tons du ciel, l'humeur des oiseaux. Il me semble difficile de mieux honorer la beaute du monde qui m'entoure que de me mettre a son diapason et de prendre la place qu'elle me laisse au sein de son choeur. C'est un jour de rythme lent, assourdi. Une marmotte curieuse s'est arretee au pied de mon camp, nous nous observons en silence.

04.

Je me figure John Muir dans la Sierra Nevada, sa communion aux precipices d'immenses cararactes; et aussi saillante que les arretes de la cordillere, son absence de peur me stupefait. Je realise que c'est elle, cette absence, qui authorise une etreinte du monde aussi totale et complete que la sienne. La peur du lendemain, la peur d'aujourd'hui, cet etat de nature aussi vieux que le monde, nous tient toujours a distance, circonspects, diminues. C'est en quoi l'aventure, cette marche enhardie vers l'inconnu, me parait necessaire: c'est elle et seulement qu'elle qui nous permet d'etre ici, maintenant et de savourer l'instant, tel qu'il est. 

05.

A propos du probleme "difficile" de la conscience. On cherche a qualifier ce qui distinguerait le "philosophe zombie" d'un etre pour qui c'est "quelque chose" que d'etre celui-ci. A savoir que l'experience du dernier est substantifiee par un je-ne-sais-quoi (on parle souvent de qualia) qui manque au premier.

Je m'interroge a savoir si, psychologiquement, ce je-ne-sais-quoi ne serait pas, du moins en partie, tributaitre a la perception du passage du temps. On pense au philosophe-zombie en tant qu'un systeme qui reproduit mecaniquement et identiquement l'exteriorite d'un etre autrement conscient. Or si l'on parle d'un systeme sous la vue Laplacienne, ultra-determinee des micro-etats qui le composent, il n'y a aucune place pour l'entropie - cette derniere emergeant d'un niveau de description qui subsume les micro-etats en macro-etats. Sans entropie qui croit irrevocablement, aucune direction ni perception du temps qui passe. Il semble que nous appliquons quelque peu instinctivement cette observation aux insectes et micro-organismes qui nous semblent de simples automates et pour qui l'action reflexe se produit pour ainsi dire, instantanement - hors du temps psychologique. Que dire maintenant d'un systeme qui, se percevant lui-meme, realisant une approximation statistique de son etat (lui-meme et son environnement), le concoit donc en termes de macro-etats des quels emergent l'entropie et sa direction. Pour un tel systeme, vieillir, le temps qui passe et le temps perdu auraient finalement un sens. J'ignore s'il s'agit la d'une condition necessaire et suffisante pour distinguer le philosophe-zombie d'un etre sensible mais bon nombre de nos impressions ont un aspect indubitablement temporel.

Question: est-ce que l'impression d'une couleur est disjointe de la dimension temporelle? Est-ce une continuite dans le temps ou bien une existence hors du temps?
    

** Notes de lecture
*** When Minds Converse
**** Agency with Judgment
- "The belief that p is a disposition robustly to act as it would be rational to act,
given the agent's other presumptively consistent beliefs and desires, if it were the
case that p: for short, to act as if p."
test
