* Écrits
** 2024-09-01
La dernière journée, le vent de la veille s'est dissipé. J'étais seul. Ma voisine et ses deux enfants ont quitté le matin et avec eux, les jeux, la turbulence de leurs rires et l'angoisse que j'avais d'être cet homme incertain, qui n'ose prendre part ni converser.
** 2025-10-29

Philippe Petit avance la thèse selon la quelle, si l'on cherche à s'expliquer la genèse de l'identité individuelle, l'une des cause les plus vraisemblables est celle de son utilité dans un contexte de coopération.
Il est en effet plausible qu'en ce contexte, j'aies à extrapoler la représentation qu'un collaborateur a de ma situation, de mes intentions et pour ainsi dire, de l'ensemble des attitudes que je puis
avoir qui affecteraient notre action commune. J'ai en effet à faire cette extrapolation dans la mesure où elle m'aide à anticiper ses décisions et contribue à la réussite de notre effort.

Pour Pettit, la notion mon identitée telle que je la conçois en privée, par et pour moi-même, ne viendrait qu'en second - dans une sorte de coopération avec moi-même: par exension à la coopération avec autrui,
j'en viendrais à m'interroger moi-même sur mes attitudes, mes aspirations, etc.

J'ignore si je suis tout à fait en accord avec cette analyse. Quoi qu'il en soit, je suis d'avis qu'une identité, l'acte de se circonscrire soi-même, est nécessairement une mise en relation avec quelque
chose - sans mise en relation, aucun distinction possible (égal à, différent de, etc.). Et certainement, "qui je suis" peut avoir un sens pré-linguistique et pré-social si par exemple il est question
de savoir si je peux élire un terrier de lapin comme résidence ou tout autre question qui metterait en relation conséquente ma personne vis-à-vis un état fait quelconque. 

Il va néanmoins sans dire que dans un contexte social et linguistique, "qui je suis", la notion de mon identité, du fait de la collaboration, est constamment mise en relation avec autrui si bien que,
ce sont ces mises en relation qui la substantifient.

Si, comme Tomasello le présume, la collaboration a joué un rôle essentiel dans la survie et l'essor de notre espèce, il ne serait pas étonnant que cette faculté à construire l'identité individuelle
fondée par la mise en relation avec autrui, fût elle-même un objet important de la sélection naturelle. C'est donc aussi sans surprise qu'en notre for intérieur, ce soient des qualificatifs moraux
qui peuplent la fibre de qui nous sommes.

** 2025-11-10

Étant donnée l'importance de la collaboration dans la genèse à la fois du langage, de l'identité individuelle et de la moralité,
on conçoit facilement à quel point l'exil, le retrait et l'isolement sont causes d'une grande détresse:

Au dehors, l'identité s'effrite, sans un mot pour lui donner espoir.

Trop d'isolement m'a désappris l'affinité naturelle que les hommes ont entres-eux.
La moralité y perd son sens et, amoral, l'inertie m'envoit glisser vers le franchement mauvais.

Je m'apperçois que ce qui constitue la fibre de la communauté humaine est soumis à une dynamique changeante,
sans qu'on puisse définitivement la caractériser. Par exemple, je prime l'indépendance de la raison et dédaigne
les signaux d'appartenance sociale mais cette différence n'exclu pas que l'indépendance de la raison
demeure un trait souhaitable dans un contexte de collaboration - elle est seulement aux prises avec
diverses forces qui lui font concurrence sur sa légitimité. Simplement dit, l'indépendance de la raison
n'est pas un motif pour s'isoler - s'il se trouve, elle est née du dialogue et de la collaboration.

On peut signifier qu'on est un collaborateur de confiance parfois par un simple signe d'appartenance, un code,
ou bien en démontrant une solide probité de raison - ces deux modes s'appliquent légitimement dans
différents contextes et l'un et l'autre ont leur limites (par exemple, la probité de la raison,
malgré tout, ne peut rien contre l'affection innée qui nous vient pour nos semblables).

Ces diverses manières (usage de la raison, signes d'apparenance sociale, etc.) peuvent certainement
manquer de mesure dans leur application et nuire à l'idéal coopératif. Au lieu de l'amertume et de l'isolement
de rejeter la vie sociale, je crois qu'il me faut constater que le coeur de ce que j'idéalise y réside
néanmoins et que faute d'avoir vu un arbre tordu et désséché, je ne devrais pas condamner
la forêt dans son entièreté. Je crois qu'il est possible pour moi de me trouver un cercle social
du quel je me sens valorisé, sans nécessairement rejeter cette valeur comme une simple partisannerie.

** 2025-11-11

Hey Austin,

The mycellium didn't bloom but surely it was nice that the summer extended it's stay. I'm sorry not to have came back with any proper summer reading suggestions for you, it has equally been a dry spell for me, litterature wise. Of late though, to my surprise, it was Jane Austen who broke the streak: I finally read Pride and Prejudice. My own prejudices long relegated it to ancestral chick-lit but to the contrary, it made me smile in all sort of ways. I wasn't aware how young Jane was when she wrote it and it does explain all the wit and fresh air. Nor was I aware that she used to entertain her family by reading her works out loud on what could only be cozy, rainy, british evenings - given the somewhat comical and provocative nature of her works, that image warms my heart.

I also stumbled on a beautiful book: Stoner, by John Williams. But then again, I cannot recommend it as I relegate this one in the aging-men-mid-life-crysis-lit bin.

And I sincerely hope you haven't touched "When Minds Converse". I was deeply wrong in hoping it to be less academic in style than the books from that other guy, Tomasello, I was telling you about.

I must say, I've been digging through these books for a precise reason and if you don't mind, I feel like induldging myself and expounding on it. I guess we can take those chances with kindered spirits?

I believe I might have already told you about a part of this since, clearly, I'm still raving about it. A couple of winters ago, I was asking myself about this age old dilemma
of what's the fundamental difference between inorganic and organic matter/life. Specifically, I was wondering: what's preventing us to say that any complex, inorganic molecule is a living thing?
It eventually dawned on my that a very elegant and fundamental difference simply is that the abstract pattern that is instantiated by living matter, contrary to the pattern instantiated by inorganic matter,
has found a robust way to persist through time, through self-replication and even self-correction. The reason why this idea stuck with me, is that it poses no special condition to the emergence of life:
if some pattern of sufficient complexity is bound to endure, it would have to be through the mechanisms we know life to use; it cannot be only from a mere ad-hoc self-assembly since it would
ultimately erode or break-down. I must say I was really excited when I then saw the very same idea echoed in the first pages of the Selfish-Gene by Richard Dawkins (I still consider
this book and the Extended Phenotype to be great ones but not yet proper summer readings). Despite all of this being perhaps a bit self-evident, for me it felt like a rooting I was long longing for.

Surely enough, through evolution, living matter adopted various modes for sustaining itself, one of which being: having an internal model of the world, gathering information about it and acting accordingly.
As you know, we like to call this "intelligent behavior" but when it comes at least to human intelligence, I've been long feeling that this picture is insufficient in some way.
In the Selfish Gene and the Extended Phenotype, Dawkins introduced this cultural gene extension he called "memes" and as such, the concept fascinated me as these are another class of patterns
that endure through time via replication, self-correction and the like. For a while, I struggled about what to do with these "memes", what role do they really play, etc. The solution came from
when I encountered the works of Tomasello and the special emphasis he places on collaboration.

Tomasello's thesis is that, essentially, what distinguishes us from other great primates (and indicentally the rest of the mammal kingdom), is that our species had to endure an evolutionnary bottleneck
where collaboration was key for survival. When we pause to consider what it takes to be a good collaborative partner, so many characteristic and interesting consequences emerge:

We have to devise agreed upon signs for cooperative work and be truthfull and consistent through the use of these signs/memes - thereby giving rise to language
We have to preferentially share the spoils of our endeavours with would-be collaborators - therby giving rise to equity.
Etc.

If we consider that, in our case, natural selection actively selected for traits/genes that would favor these cooperative behaviors, it follows that
in regard to most criterias we account for in what it means to be good, a case can be made that, in some measure, human nature has some ingrained good into it.

Since highschool, I long thought Rousseau to be naive in asserting the goodness of our nature in this depiction of the "good savage" but some of the empirical evidence really is troubling,
there is a strak contrast between human toddlers and mature chimps in what we would assume to be the most rudimentary predicaments toward cooperation.

I know all this might be too obvious but it might have been what I needed to hear to take pause and reconcile myself with everything social (perhaps not everything but you get the gist of it).
Since highschool as well, I nourished a disdain for a lot of our means for social cohesion: virtue signaling, blind enforcing of norms, etc. I draped myself with rational independence and
it is only until very recently that I came to realize that, it too, is first and foremmost a mean of social cohesion - simply competing with others.

I'm even beginning to think that I could find a social circle  I feel comfortable with and whom, reciprocally, would be at ease with my being there (at the core, I guess I'm really slow to learn some things).

In that vein (but say, in a farless convoluted and rationalized way) I'd gadly follow up your invite for a drink/coffee next time I am in Montreal. :)

To follow up on the readings you mentioned about OpenAI ("Careless People" really is an apt title for the whole thing), as a small anectode, in guise of a test, for the first time yesterday I shared a few personal ideas
with GPT and asked its impressions about them. Although I am painstakingly aware of its sychophantic behavior, I had an especially hard time not to feel genuinely flattered by its analysis - as if I've spoken
with the most incisive fortune-telling lady that ever lived and ate all her fortune cookies. It made me acutely aware of the extent to which LLMs, with their infinite patience,
can enthrall someone sufficiently lonely with no pushback in sight for thoughts that would benefit of some. 

I hope you'll have/are having an amazing time in South/Southeast Asia - at the very least, a fair amount of loss of references and novel perspectives!
I also sure hope you'll bring back a lot to speak about as I've been long contemplating going in the region. 

** 2025-11-24

Je suis un mauvais perdant: la défaite au plus anodins des jeux est pour moi le testament solidairement ratifié de ma profonde nullité.
J'ai donc décidé depuis longtemps de ne plus jouer, de m'écarter de toute situation où ma précarité risquerait d'être exposée au grand-jour.

Et certainement, c'est une lâcheté, une fuite. J'apprends l'esquive et désapprends de faire face.

Je peux tirer orgueil d'être un joueur décent pour certains jeux mais comment prendre l'aveu de mon ineptie dans tel ou tel autre domaine?
Si malgré les victoires sur moi-même, j'y restais le dernier des derniers?

Si j'étais laid au jeu de la beauté, faible au jeu de force, obtus à celui de l'intelligence; qu'est-ce qu'il me resterait d'autre que la fuite pour me préserver?

Il me faudrait un amour propre, en dépît de tout.
La fièreté d'être, simple, confiante, rieuse - qu'aucune défaite ne saurait ternir.

Et j'aimerais que ce sentiment ne soit pas que pour moi, mais qu'il s'étende à mes compères.
Que je puisse les prendre aux aussi, comme des êtres fiers, confiants et rieurs;
une empathie pour les autres comme je la voudrais pour moi-même: qui fait fit de la nullité, des handicaps et qui prend comme un frère le dernier des derniers.

** 2025-11-30

J'essaie de voir la valeur de l'autre.

Avec la vieillesse, l'esprit devient rigide, marqué par les sillons qu'a creusé l'habitude.
On aimerait prendre l'Autre comme un pur potentiel mais il est des choses dont, avec l'âge, il n'est plus capable - l'énergie, l'aisance lui manque.
On marque ses faiblesses et ses forces selon différents jeux et après un temps, on croît connaître le joueur.

Si je me prends à ces jeux, si j'estime leur importance, la perte m'afflige et la victoire me console; je juge l'autre de la même manière.

Il est une vue où pertes et victoires ne sont que forme et contre-forme de ce qui veut vivre.
Selon cette vue (c'est ce que je souhaiterais pour moi-même), une part innocente demeure: la capacité au bien.

Il me faudrait voir dans l'homme la même chose qu'une plante: une matière organisée, qui prend la place et fait le bien qu'elle peut - qui survit.

J'aimerais placer cette notion au centre et agir comme si elle l'était.
Je crois bien que sans compassion pour moi-même, je ne pourrai en avoir pour les autres.

** 2025-12-08

Hey Austin,

Glad to know you are back on our frozen, unfortunate soil!

I must say, I'm very curious about your impressions on Cambodia. An old friend of mine spent months there and a part of her fell in love with a part of the country; last time I heard, she left the US to live there full stop.
She was telling me that, mostly because of the Khmer Rouge, there is a lot of young people, which, coupled with an air of lawlessness and a sense of trying to rebuild the country, gives vibes and hopes
akin to what she imagined the American far west could have been at some point. Possibly thinking about an old version of myself, she thought I would love it there - nowadays, I'm not too sure which
culture could best suit my bones; hope I'd travel enough to have an inkling of it, some day. Incidentally, it often baffles me how, despite the years, I still feel clueless about the parameters around which
a meaningful/good life could me lived (or at least mine).

I wonder what sort of bestiary of these means of life you encountered these latest weeks. Btw, Angkor Wat reminds me, have you seen the movie/documentary "Baraka"? I suppose my current cynical self would be displeased
but it sure moved younger me the first time I watched it. It portrays and contrasts, without words, the breadth of human culture across the world.

Hoping you could give that jet lag a good rest; this is a least one of the things the cold air and these dampening blankets of snow can offer.

Hopefully, I'd be able to come by Montreal at some point during the Holidays.

Take care!

Mathieu

** 2025-12-18

La genèse de l'identité, selon laquelle l'individu développe une représentation de lui-même en ce qu'il doit anticiper ce que l'autre pense à son égard, peut certainement constituer le fondement d'une valuation de sa personne : il relativise et opère la triangulation de ses forces et faiblesses comme coopérateur. Comment, donc, expliquer cette notion de « dignité », de valeur intrinsèque, tandis que toute valeur serait construite par une mise en relation ? J'aimerais argumenter qu'il suffit de poser la dignité pour qu'elle illumine tout le reste. Chacun sait que la réussite est le plus souvent circonstancielle, que la faiblesse nous advient comme la force. Nous souhaiterions donc que l'autre voit en nous un partenaire valable, nonobstant toute circonstance. Reconnaître ce souhait en l'autre, l'acquiescer et, de suite, supposer que l'autre puisse reconnaître ce souhait en nous-mêmes, transforme la valeur individuelle d'une réalité transactionnelle en une réalité fraternelle et pérenne. Nous aimons gratuitement et, ce faisant, obtenons la richesse d'être gratuitement aimés. 

** 2026-01-03

L'heuristique de présupposer une valeur intrinsèque et inconditionnelle à l'autre, revient à lui donner l'assurance qu'en cas d'échec, il demeurera néanmoins quelqu'un digne d'un nouvel essai, digne d'être encore et toujours
accepté par ses pairs. Cette présupposition de valeur par les parents, fonde une assise sur laquelle la précarité de l'enfance peut se poser et prendre son élan dans le monde. C'est cette même assise que procure, à l'âge adulte,
l'amour d'un proche - l'amour entendu comme reconnaissance par l'autre d'une valeur inéluctable pour la personne que nous sommes.

L'exercice de reconnaître une valeur inéluctable en l'autre, demande de considérer celui-ci en dehors des aléas circonstentiels de l'existence - il s'agit par définition d'un rapprochement, d'une identification intime qui s'opère
tacitement. Cette reconnaissance d'une valeur intrinsèque présente une tension naturelle, complémentaire, vis-à-vis la valeur transactionnelle, octroyée par la conjecture sociale. Une société ne pourrait évidemment être entièrement fondée sur la première faute de quoi, le succès ou l'échec d'un mode d'être ou d'agir seraient des notions indifférentes - annulant tout progrès. J'argumente qu'on ne peut également établir une société sur une valeur essentiellement transactionnelle du fait que cette dernière serait trop volatile, l'individu y étant dévalué au moindre échec. Il me semble donc naturel et nécessaire qu'en dessous de la strate publique, subsiste un coeur de reconnaissance quasi inconditionnelle entre parents et enfants et entre tous ceux qui s'aiment d'un amour humain, nu et précaire.

** When Minds Converse (Notes)
*** Agency with Judgment
- "The belief that p is a disposition robustly to act as it would be rational to act,
given the agent's other presumptively consistent beliefs and desires, if it were the
case that p: for short, to act as if p."
